In [1]:
import pandas as pd
import yfinance as yf
from pathlib import Path

print("Librerías cargadas correctamente")

Librerías cargadas correctamente

In [2]:
ticker = "SPY"
start_date = "1993-01-01"

project_root = Path.cwd().parent
raw_data_path = project_root / "data" / "raw"
raw_data_path.mkdir(parents=True, exist_ok=True)

output_file = raw_data_path / "SPY_daily.csv"

print("Carpeta de datos:", raw_data_path)
print("Archivo de salida:", output_file)

Carpeta de datos: c:\Users\usuario\Documents\GitHub\QuantLab\data\raw
Archivo de salida: c:\Users\usuario\Documents\GitHub\QuantLab\data\raw\SPY_daily.csv

In [11]:
# Descargamos datos originales
spy_raw = yf.download(
    ticker,
    start=start_date,
    auto_adjust=False,
    progress=False
)

spy_raw.head()

Price       Adj Close     Close      High       Low      Open   Volume
Ticker            SPY       SPY       SPY       SPY       SPY      SPY
Date
1993-01-29  24.113268  43.93750  43.96875  43.75000  43.96875  1003200
1993-02-01  24.284761  44.25000  44.25000  43.96875  43.96875   480500
1993-02-02  24.336224  44.34375  44.37500  44.12500  44.21875   201300
1993-02-03  24.593477  44.81250  44.84375  44.37500  44.40625   529400
1993-02-04  24.696363  45.00000  45.09375  44.46875  44.96875   531500

In [12]:
raw_output_file = raw_data_path / "SPY_daily_raw.csv"
spy_raw.to_csv(raw_output_file)

In [13]:
spy = spy_raw.copy()

if isinstance(spy.columns, pd.MultiIndex):
    spy.columns = spy.columns.get_level_values(0)

spy.head()

Price       Adj Close     Close      High       Low      Open   Volume
Date
1993-01-29  24.113268  43.93750  43.96875  43.75000  43.96875  1003200
1993-02-01  24.284761  44.25000  44.25000  43.96875  43.96875   480500
1993-02-02  24.336224  44.34375  44.37500  44.12500  44.21875   201300
1993-02-03  24.593477  44.81250  44.84375  44.37500  44.40625   529400
1993-02-04  24.696363  45.00000  45.09375  44.46875  44.96875   531500

In [14]:
processed_data_path = project_root / "data" / "processed"
processed_data_path.mkdir(parents=True, exist_ok=True)

processed_output_file = processed_data_path / "SPY_daily.csv"
spy.to_csv(processed_output_file)

In [4]:
spy.tail()

Price,Adj Close,Close,High,Low,Open,Volume
Ticker,SPY,SPY,SPY,SPY,SPY,SPY
Date,,,,,,
2026-06-26,728.989990,728.989990,736.530029,716.580017,728.950012,71034000
2026-06-29,741.000000,741.000000,741.559998,732.090027,736.530029,58035200
2026-06-30,746.770020,746.770020,748.020020,740.890015,741.289978,55626000
2026-07-01,745.760010,745.760010,749.440002,742.380005,745.000000,47100900
2026-07-02,744.780029,744.780029,751.309998,740.030029,747.400024,57447800

In [5]:
spy.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 8413 entries, 1993-01-29 to 2026-07-02
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   (Adj Close, SPY)  8413 non-null   float64
 1   (Close, SPY)      8413 non-null   float64
 2   (High, SPY)       8413 non-null   float64
 3   (Low, SPY)        8413 non-null   float64
 4   (Open, SPY)       8413 non-null   float64
 5   (Volume, SPY)     8413 non-null   int64
dtypes: float64(5), int64(1)
memory usage: 460.1 KB

In [6]:
spy.isna().sum()

Price      Ticker
Adj Close  SPY       0
Close      SPY       0
High       SPY       0
Low        SPY       0
Open       SPY       0
Volume     SPY       0
dtype: int64

In [7]:
spy.to_csv(output_file)

print(f"Datos guardados en: {output_file}")

Datos guardados en: c:\Users\usuario\Documents\GitHub\QuantLab\data\raw\SPY_daily.csv

In [8]:
spy_check = pd.read_csv(output_file, index_col=0, parse_dates=True)

spy_check.head()

C:\Users\usuario\AppData\Local\Temp\ipykernel_10488\901721407.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  spy_check = pd.read_csv(output_file, index_col=0, parse_dates=True)

,Adj Close,Close,High,Low,Open,Volume
Price,,,,,,
Ticker,SPY,SPY,SPY,SPY,SPY,SPY
Date,NaN,NaN,NaN,NaN,NaN,NaN
1993-01-29,24.113250732421875,43.9375,43.96875,43.75,43.96875,1003200
1993-02-01,24.284757614135742,44.25,44.25,43.96875,43.96875,480500
1993-02-02,24.336212158203125,44.34375,44.375,44.125,44.21875,201300

In [9]:
spy_check.shape

(8415, 6)